/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface EncryptedMultisigInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_CALLDATA_CHUNKS"
      | "addSigner"
      | "approve"
      | "cancel"
      | "createProposal"
      | "dao"
      | "execute"
      | "finalize"
      | "getProposalInfo"
      | "getRevealedChunks"
      | "isTrustedForwarder"
      | "proposalCount"
      | "proposalDuration"
      | "removeSigner"
      | "revealProposal"
      | "setThreshold"
      | "signerCount"
      | "state"
      | "threshold"
      | "trustedForwarder"
      | "viewProposal"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approved"
      | "ProposalCancelled"
      | "ProposalCreated"
      | "ProposalExecuted"
      | "ProposalFinalized"
      | "ProposalRevealed"
      | "ProposalViewed"
      | "PublicDecryptionVerified"
      | "SignerCountUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_CALLDATA_CHUNKS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancel",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createProposal",
    values: [BytesLike[], BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "dao", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalize",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRevealedChunks",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isTrustedForwarder",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposalCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposalDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revealProposal",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "signerCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "state", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "threshold", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "trustedForwarder",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "viewProposal",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_CALLDATA_CHUNKS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addSigner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dao", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "finalize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProposalInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRevealedChunks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTrustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposalDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revealProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "state", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "threshold", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "trustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "viewProposal",
    data: BytesLike
  ): Result;
}

export namespace ApprovedEvent {
  export type InputTuple = [proposalId: BigNumberish];
  export type OutputTuple = [proposalId: bigint];
  export interface OutputObject {
    proposalId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalCancelledEvent {
  export type InputTuple = [proposalId: BigNumberish];
  export type OutputTuple = [proposalId: bigint];
  export interface OutputObject {
    proposalId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalCreatedEvent {
  export type InputTuple = [proposalId: BigNumberish];
  export type OutputTuple = [proposalId: bigint];
  export interface OutputObject {
    proposalId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalExecutedEvent {
  export type InputTuple = [proposalId: BigNumberish];
  export type OutputTuple = [proposalId: bigint];
  export interface OutputObject {
    proposalId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalFinalizedEvent {
  export type InputTuple = [proposalId: BigNumberish, approved: boolean];
  export type OutputTuple = [proposalId: bigint, approved: boolean];
  export interface OutputObject {
    proposalId: bigint;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalRevealedEvent {
  export type InputTuple = [proposalId: BigNumberish];
  export type OutputTuple = [proposalId: bigint];
  export interface OutputObject {
    proposalId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalViewedEvent {
  export type InputTuple = [proposalId: BigNumberish];
  export type OutputTuple = [proposalId: bigint];
  export interface OutputObject {
    proposalId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PublicDecryptionVerifiedEvent {
  export type InputTuple = [
    handlesList: BytesLike[],
    abiEncodedCleartexts: BytesLike
  ];
  export type OutputTuple = [
    handlesList: string[],
    abiEncodedCleartexts: string
  ];
  export interface OutputObject {
    handlesList: string[];
    abiEncodedCleartexts: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignerCountUpdatedEvent {
  export type InputTuple = [newCount: BigNumberish];
  export type OutputTuple = [newCount: bigint];
  export interface OutputObject {
    newCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EncryptedMultisig extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedMultisig;
  waitForDeployment(): Promise<this>;

  interface: EncryptedMultisigInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_CALLDATA_CHUNKS: TypedContractMethod<[], [bigint], "view">;

  addSigner: TypedContractMethod<[signer: AddressLike], [void], "nonpayable">;

  approve: TypedContractMethod<
    [proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancel: TypedContractMethod<
    [proposalId: BigNumberish, cancelKey: BytesLike],
    [void],
    "nonpayable"
  >;

  createProposal: TypedContractMethod<
    [encHandles: BytesLike[], inputProof: BytesLike, cancelKeyHash: BytesLike],
    [bigint],
    "nonpayable"
  >;

  dao: TypedContractMethod<[], [string], "view">;

  execute: TypedContractMethod<
    [proposalId: BigNumberish, allowFailureMap: BigNumberish],
    [void],
    "nonpayable"
  >;

  finalize: TypedContractMethod<
    [
      proposalId: BigNumberish,
      decryptionProof: BytesLike,
      abiEncodedCleartexts: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getProposalInfo: TypedContractMethod<
    [proposalId: BigNumberish],
    [
      [bigint, bigint, bigint, boolean, boolean, boolean, boolean, boolean] & {
        createdAt: bigint;
        expiresAt: bigint;
        chunkCount: bigint;
        finalized: boolean;
        resultApproved: boolean;
        revealed: boolean;
        executed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;

  getRevealedChunks: TypedContractMethod<
    [proposalId: BigNumberish],
    [bigint[]],
    "view"
  >;

  isTrustedForwarder: TypedContractMethod<
    [forwarder: AddressLike],
    [boolean],
    "view"
  >;

  proposalCount: TypedContractMethod<[], [bigint], "view">;

  proposalDuration: TypedContractMethod<[], [bigint], "view">;

  removeSigner: TypedContractMethod<
    [signer: AddressLike],
    [void],
    "nonpayable"
  >;

  revealProposal: TypedContractMethod<
    [
      proposalId: BigNumberish,
      decryptionProof: BytesLike,
      abiEncodedCleartexts: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setThreshold: TypedContractMethod<
    [newThreshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  signerCount: TypedContractMethod<[], [bigint], "view">;

  state: TypedContractMethod<[proposalId: BigNumberish], [bigint], "view">;

  threshold: TypedContractMethod<[], [bigint], "view">;

  trustedForwarder: TypedContractMethod<[], [string], "view">;

  viewProposal: TypedContractMethod<
    [proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_CALLDATA_CHUNKS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addSigner"
  ): TypedContractMethod<[signer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<[proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancel"
  ): TypedContractMethod<
    [proposalId: BigNumberish, cancelKey: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createProposal"
  ): TypedContractMethod<
    [encHandles: BytesLike[], inputProof: BytesLike, cancelKeyHash: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "dao"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [proposalId: BigNumberish, allowFailureMap: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalize"
  ): TypedContractMethod<
    [
      proposalId: BigNumberish,
      decryptionProof: BytesLike,
      abiEncodedCleartexts: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getProposalInfo"
  ): TypedContractMethod<
    [proposalId: BigNumberish],
    [
      [bigint, bigint, bigint, boolean, boolean, boolean, boolean, boolean] & {
        createdAt: bigint;
        expiresAt: bigint;
        chunkCount: bigint;
        finalized: boolean;
        resultApproved: boolean;
        revealed: boolean;
        executed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRevealedChunks"
  ): TypedContractMethod<[proposalId: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "isTrustedForwarder"
  ): TypedContractMethod<[forwarder: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "proposalCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proposalDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "removeSigner"
  ): TypedContractMethod<[signer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revealProposal"
  ): TypedContractMethod<
    [
      proposalId: BigNumberish,
      decryptionProof: BytesLike,
      abiEncodedCleartexts: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setThreshold"
  ): TypedContractMethod<[newThreshold: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "signerCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "state"
  ): TypedContractMethod<[proposalId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "threshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "trustedForwarder"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "viewProposal"
  ): TypedContractMethod<[proposalId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "Approved"
  ): TypedContractEvent<
    ApprovedEvent.InputTuple,
    ApprovedEvent.OutputTuple,
    ApprovedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalCancelled"
  ): TypedContractEvent<
    ProposalCancelledEvent.InputTuple,
    ProposalCancelledEvent.OutputTuple,
    ProposalCancelledEvent.OutputObject
  >;
  getEvent(
    key: "ProposalCreated"
  ): TypedContractEvent<
    ProposalCreatedEvent.InputTuple,
    ProposalCreatedEvent.OutputTuple,
    ProposalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalExecuted"
  ): TypedContractEvent<
    ProposalExecutedEvent.InputTuple,
    ProposalExecutedEvent.OutputTuple,
    ProposalExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalFinalized"
  ): TypedContractEvent<
    ProposalFinalizedEvent.InputTuple,
    ProposalFinalizedEvent.OutputTuple,
    ProposalFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalRevealed"
  ): TypedContractEvent<
    ProposalRevealedEvent.InputTuple,
    ProposalRevealedEvent.OutputTuple,
    ProposalRevealedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalViewed"
  ): TypedContractEvent<
    ProposalViewedEvent.InputTuple,
    ProposalViewedEvent.OutputTuple,
    ProposalViewedEvent.OutputObject
  >;
  getEvent(
    key: "PublicDecryptionVerified"
  ): TypedContractEvent<
    PublicDecryptionVerifiedEvent.InputTuple,
    PublicDecryptionVerifiedEvent.OutputTuple,
    PublicDecryptionVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "SignerCountUpdated"
  ): TypedContractEvent<
    SignerCountUpdatedEvent.InputTuple,
    SignerCountUpdatedEvent.OutputTuple,
    SignerCountUpdatedEvent.OutputObject
  >;

  filters: {
    "Approved(uint256)": TypedContractEvent<
      ApprovedEvent.InputTuple,
      ApprovedEvent.OutputTuple,
      ApprovedEvent.OutputObject
    >;
    Approved: TypedContractEvent<
      ApprovedEvent.InputTuple,
      ApprovedEvent.OutputTuple,
      ApprovedEvent.OutputObject
    >;

    "ProposalCancelled(uint256)": TypedContractEvent<
      ProposalCancelledEvent.InputTuple,
      ProposalCancelledEvent.OutputTuple,
      ProposalCancelledEvent.OutputObject
    >;
    ProposalCancelled: TypedContractEvent<
      ProposalCancelledEvent.InputTuple,
      ProposalCancelledEvent.OutputTuple,
      ProposalCancelledEvent.OutputObject
    >;

    "ProposalCreated(uint256)": TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
    ProposalCreated: TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;

    "ProposalExecuted(uint256)": TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;
    ProposalExecuted: TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;

    "ProposalFinalized(uint256,bool)": TypedContractEvent<
      ProposalFinalizedEvent.InputTuple,
      ProposalFinalizedEvent.OutputTuple,
      ProposalFinalizedEvent.OutputObject
    >;
    ProposalFinalized: TypedContractEvent<
      ProposalFinalizedEvent.InputTuple,
      ProposalFinalizedEvent.OutputTuple,
      ProposalFinalizedEvent.OutputObject
    >;

    "ProposalRevealed(uint256)": TypedContractEvent<
      ProposalRevealedEvent.InputTuple,
      ProposalRevealedEvent.OutputTuple,
      ProposalRevealedEvent.OutputObject
    >;
    ProposalRevealed: TypedContractEvent<
      ProposalRevealedEvent.InputTuple,
      ProposalRevealedEvent.OutputTuple,
      ProposalRevealedEvent.OutputObject
    >;

    "ProposalViewed(uint256)": TypedContractEvent<
      ProposalViewedEvent.InputTuple,
      ProposalViewedEvent.OutputTuple,
      ProposalViewedEvent.OutputObject
    >;
    ProposalViewed: TypedContractEvent<
      ProposalViewedEvent.InputTuple,
      ProposalViewedEvent.OutputTuple,
      ProposalViewedEvent.OutputObject
    >;

    "PublicDecryptionVerified(bytes32[],bytes)": TypedContractEvent<
      PublicDecryptionVerifiedEvent.InputTuple,
      PublicDecryptionVerifiedEvent.OutputTuple,
      PublicDecryptionVerifiedEvent.OutputObject
    >;
    PublicDecryptionVerified: TypedContractEvent<
      PublicDecryptionVerifiedEvent.InputTuple,
      PublicDecryptionVerifiedEvent.OutputTuple,
      PublicDecryptionVerifiedEvent.OutputObject
    >;

    "SignerCountUpdated(uint256)": TypedContractEvent<
      SignerCountUpdatedEvent.InputTuple,
      SignerCountUpdatedEvent.OutputTuple,
      SignerCountUpdatedEvent.OutputObject
    >;
    SignerCountUpdated: TypedContractEvent<
      SignerCountUpdatedEvent.InputTuple,
      SignerCountUpdatedEvent.OutputTuple,
      SignerCountUpdatedEvent.OutputObject
    >;
  };
}
