/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IDAO {
  export type ActionStruct = {
    to: AddressLike;
    value: BigNumberish;
    data: BytesLike;
  };

  export type ActionStructOutput = [to: string, value: bigint, data: string] & {
    to: string;
    value: bigint;
    data: string;
  };
}

export interface IDAOInterface extends Interface {
  getFunction(nameOrSignature: "execute" | "hasPermission"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ETHDeposited" | "Executed"): EventFragment;

  encodeFunctionData(
    functionFragment: "execute",
    values: [BytesLike, IDAO.ActionStruct[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPermission",
    values: [AddressLike, AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasPermission",
    data: BytesLike
  ): Result;
}

export namespace ETHDepositedEvent {
  export type InputTuple = [sender: AddressLike, amount: BigNumberish];
  export type OutputTuple = [sender: string, amount: bigint];
  export interface OutputObject {
    sender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutedEvent {
  export type InputTuple = [
    callId: BytesLike,
    actor: AddressLike,
    actions: IDAO.ActionStruct[],
    allowFailureMap: BigNumberish,
    failureMap: BigNumberish
  ];
  export type OutputTuple = [
    callId: string,
    actor: string,
    actions: IDAO.ActionStructOutput[],
    allowFailureMap: bigint,
    failureMap: bigint
  ];
  export interface OutputObject {
    callId: string;
    actor: string;
    actions: IDAO.ActionStructOutput[];
    allowFailureMap: bigint;
    failureMap: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IDAO extends BaseContract {
  connect(runner?: ContractRunner | null): IDAO;
  waitForDeployment(): Promise<this>;

  interface: IDAOInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  execute: TypedContractMethod<
    [
      callId: BytesLike,
      actions: IDAO.ActionStruct[],
      allowFailureMap: BigNumberish
    ],
    [[string[], bigint] & { results: string[]; failureMap: bigint }],
    "nonpayable"
  >;

  hasPermission: TypedContractMethod<
    [where: AddressLike, who: AddressLike, permissionId: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [
      callId: BytesLike,
      actions: IDAO.ActionStruct[],
      allowFailureMap: BigNumberish
    ],
    [[string[], bigint] & { results: string[]; failureMap: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasPermission"
  ): TypedContractMethod<
    [where: AddressLike, who: AddressLike, permissionId: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "ETHDeposited"
  ): TypedContractEvent<
    ETHDepositedEvent.InputTuple,
    ETHDepositedEvent.OutputTuple,
    ETHDepositedEvent.OutputObject
  >;
  getEvent(
    key: "Executed"
  ): TypedContractEvent<
    ExecutedEvent.InputTuple,
    ExecutedEvent.OutputTuple,
    ExecutedEvent.OutputObject
  >;

  filters: {
    "ETHDeposited(address,uint256)": TypedContractEvent<
      ETHDepositedEvent.InputTuple,
      ETHDepositedEvent.OutputTuple,
      ETHDepositedEvent.OutputObject
    >;
    ETHDeposited: TypedContractEvent<
      ETHDepositedEvent.InputTuple,
      ETHDepositedEvent.OutputTuple,
      ETHDepositedEvent.OutputObject
    >;

    "Executed(bytes32,address,tuple[],uint256,uint256)": TypedContractEvent<
      ExecutedEvent.InputTuple,
      ExecutedEvent.OutputTuple,
      ExecutedEvent.OutputObject
    >;
    Executed: TypedContractEvent<
      ExecutedEvent.InputTuple,
      ExecutedEvent.OutputTuple,
      ExecutedEvent.OutputObject
    >;
  };
}
